[changelog]
# Header for the changelog
header = "# Changelog\n\n"
# Template for the changelog body
body = """
{% if version %}\
## {{ version }} {% if timestamp %}({{ timestamp | date(format="%Y-%m-%d") }}){% endif %}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{{ commit.message | upper_first }}{% if commit.id %} ({{ commit.id | truncate(length=7, end="") }}){% endif %}
{% endfor %}
{% endfor %}
"""
# Remove the leading and trailing whitespace from the template
trim = true


[git]
conventional_commits = true
filter_unconventional = false
tag_pattern = "v[0-9]*"
commit_parsers = [
    { message = "^feat(?:\\(([^)]+)\\))?\\s*:\\s*(.+)", group = "Features", scope = "$1", subject = "$2" },
    { message = "^fix(?:\\(([^)]+)\\))?\\s*:\\s*(.+)", group = "Bug Fixes", scope = "$1", subject = "$2" },
    { message = "^doc(?:\\(([^)]+)\\))?\\s*:\\s*(.+)", group = "Documentation", scope = "$1", subject = "$2" },
    { message = "^perf(?:\\(([^)]+)\\))?\\s*:\\s*(.+)", group = "Performance", scope = "$1", subject = "$2" },
    { message = "^refactor(?:\\(([^)]+)\\))?\\s*:\\s*(.+)", group = "Refactor", scope = "$1", subject = "$2" },
    { message = "^style(?:\\(([^)]+)\\))?\\s*:\\s*(.+)", group = "Styling", scope = "$1", subject = "$2" },
    { message = "^test(?:\\(([^)]+)\\))?\\s*:\\s*(.+)", group = "Testing", scope = "$1", subject = "$2" },
    { message = "^chore(?:\\(([^)]+)\\))?\\s*:\\s*(.+)", group = "Chore", scope = "$1", subject = "$2" },
    { message = ".*", group = "Other", default_scope = "other"},
]